{
 "title": "Jaeger Agent",
 "description": "Jaeger Agent dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(jaeger_agent_thrift_udp_server_queue_size, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Reporter Batch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reporter batch size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_agent_reporter_batch_size{format=\"jaeger\",protocol=\"grpc\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reporter batches submitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_submitted_total{format=\"jaeger\",protocol=\"grpc\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reporter batches failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total{format=\"jaeger\",protocol=\"grpc\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Reporter Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reporter spans submitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_submitted_total{format=\"jaeger\",protocol=\"grpc\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reporter spans failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_failures_total{format=\"jaeger\",protocol=\"grpc\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Receiver UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_agent_thrift_udp_server_queue_size{model=\"jaeger\",protocol=\"compact\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_read_errors_total{model=\"jaeger\",protocol=\"compact\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packet size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_agent_thrift_udp_server_packet_size{model=\"jaeger\",protocol=\"compact\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_packets_processed_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_packets_dropped_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}