version: '2'
x-es-environment-defaults:
  C1: &DISCOVERY_SEED_HOSTS "discovery.seed_hosts=es_1:9300,es_2:9300,es_3:9300"
  C2: &CLUSTER_INITIAL_MASTER_NODES "cluster.initial_master_nodes=es_1,es_2,es_3"
  C4: &ES_JAVA_OPTS "ES_JAVA_OPTS=\
        -Xms1g \
        -Xmx1g \
      "

x-es-ulimit-defaults: &ES_ULIMIT_DEFAULTS
  nproc: 65535
  nofile:
    soft: 65535
    hard: 65535
  memlock:
    soft: -1
    hard: -1

networks:
  net:
    driver: "bridge"

volumes:
  es_vol_1_logs:
    driver: "local"
  es_vol_1_data:
    driver: "local"
  es_vol_2_logs:
    driver: "local"
  es_vol_2_data:
    driver: "local"
  es_vol_3_logs:
    driver: "local"
  es_vol_3_data:
    driver: "local"

x-es-logging-defaults: &ES_LOGGING_DEFAULTS
  driver: "json-file"
  options:
    max-size: "512m"

services:
  kibana:
    image: "kibana:7.0.0"
    container_name: "kibana"
    hostname: "kibana"
    depends_on:
      - "es_1"
#      - "es_2"
#      - "es_3"
    networks:
      - "net"
    ports:
      - "5601:5601"
    restart: "always"
    logging:
      <<: *ES_LOGGING_DEFAULTS
    environment:
      - SERVER_PORT=5601
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=es_cluster
      - ELASTICSEARCH_HOSTS=["http://es_1:9200"]
      - KIBANA_INDEX=.kibana
      - DIBANA_DEFAULTAPPID=home
      - ELASTICSEARCH_PINGTIMEOUT=1500
      - ELASTICSEARCH_REQUESTTIMEOUT=10000
      - ELASTICSEARCH_LOGQUERIES=false
  filebeat:
    image: "elastic/filebeat:7.0.0"
    container_name: "filebeat"
    hostname: "filebeat"
    depends_on:
      - "es_1"
#      - "es_2"
#      - "es_3"
    networks:
      - "net"
    volumes:
      - /private/tmp/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - /private/tmp/logs/app:/tmp/app/logs
    restart: "always"
    logging:
      <<: *ES_LOGGING_DEFAULTS
    environment:
#      - ES_HOSTS=es_1:9200,es_2:9200,es_3:9200
      - ES_HOSTS=es_1:9200
      - LOGGING_LEVEL=debug # error, warning, info, debug
      - NUM_OF_OUTPUT_WORKERS=9 # node count * 3, 3 workers per node
      - NUM_OF_SHARDS=3
      - NUM_OF_REPLICAS=1 # replicas count per shard, total count is num_of_shards * (1 + num_of_replicas)
  es_1:
    image: "elasticsearch:7.1.1"
    container_name: "es_1"
    hostname: "es_1"
    volumes:
      - es_vol_1_data:/usr/share/elasticsearch/data
      - es_vol_1_logs:/usr/share/elasticsearch/logs
    networks:
      - "net"
    ports:
      - "9201:9200"
    restart: "always"
    logging:
      <<: *ES_LOGGING_DEFAULTS
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - *ES_JAVA_OPTS
    ulimits:
      <<: *ES_ULIMIT_DEFAULTS
#  es_1:
#    image: "elasticsearch:7.0.0"
#    container_name: "es_1"
#    hostname: "es_1"
#    volumes:
#      - es_vol_1_data:/usr/share/elasticsearch/data
#      - es_vol_1_logs:/usr/share/elasticsearch/logs
#      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
#    networks:
#      - "net"
#    ports:
#      - "9201:9200"
#    expose:
#      - "9300"
#    restart: "always"
#    logging:
#      <<: *ES_LOGGING_DEFAULTS
#    environment:
#      - node.name=es_1
#      - http.port=9200
#      - transport.tcp.port=9300
#      - node.master=true
#      - node.data=true
#      - *DISCOVERY_SEED_HOSTS
#      - *CLUSTER_INITIAL_MASTER_NODES
#      - *ES_JAVA_OPTS
#    ulimits:
#      <<: *ES_ULIMIT_DEFAULTS
#  es_2:
#    image: "elasticsearch:7.0.0"
#    container_name: "es_2"
#    hostname: "es_2"
#    volumes:
#      - es_vol_2_data:/usr/share/elasticsearch/data
#      - es_vol_2_logs:/usr/share/elasticsearch/logs
#      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
#    networks:
#      - "net"
#    ports:
#      - "9202:9200"
#    expose:
#      - "9300"
#    restart: "always"
#    logging:
#      <<: *ES_LOGGING_DEFAULTS
#    environment:
#      - node.name=es_2
#      - http.port=9200
#      - transport.tcp.port=9300
#      - node.master=true
#      - node.data=true
#      - *DISCOVERY_SEED_HOSTS
#      - *CLUSTER_INITIAL_MASTER_NODES
#      - *ES_JAVA_OPTS
#    ulimits:
#      <<: *ES_ULIMIT_DEFAULTS
#  es_3:
#    image: "elasticsearch:7.0.0"
#    container_name: "es_3"
#    hostname: "es_3"
#    volumes:
#      - es_vol_3_data:/usr/share/elasticsearch/data
#      - es_vol_3_logs:/usr/share/elasticsearch/logs
#      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
#    networks:
#      - "net"
#    ports:
#      - "9203:9200"
#    expose:
#      - "9300"
#    restart: "always"
#    logging:
#      <<: *ES_LOGGING_DEFAULTS
#    environment:
#      - node.name=es_3
#      - http.port=9200
#      - transport.tcp.port=9300
#      - node.master=true
#      - node.data=true
#      - *DISCOVERY_SEED_HOSTS
#      - *CLUSTER_INITIAL_MASTER_NODES
#      - *ES_JAVA_OPTS
#    ulimits:
#      <<: *ES_ULIMIT_DEFAULTS
  es_exporter:
    image: "justwatch/elasticsearch_exporter:1.1.0rc1"
    container_name: "es_exporter"
    hostname: "es_exporter"
    depends_on:
      - "es_1"
#      - "es_2"
#      - "es_3"
    networks:
      - "net"
    ports:
      - "9114:9114"
    expose:
      - "9114"
    restart: "always"
    logging:
      <<: *ES_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9114",
      "--web.telemetry-path=/metrics",
      "--es.uri=http://es_1:9200",
      "--es.all",
      "--es.cluster_settings",
      "--es.shards",
      "--es.indices",
      "--es.indices_settings",
      "--es.snapshots",
      "--log.level=info",
      "--log.format=json",
      "--log.output=stdout",
    ]