version: '2'

x-jaeger-defaults:
  C01: &ES_SERVER_URLS "--es.server-urls=http://es_1:9201,http://es_2:9202,http://es_3:9203"
  C02: &ES_NUM_SHARDS "--es.num-shards=3"
  C03: &ES_NUM_REPLICAS "--es.num-replicas=1"
  C04: &LOG_LEVEL_DEBUG "--log-level=debug"
  C05: &METRICS_BACKEND "--metrics-backend=prometheus"
  C06: &METRICS_HTTP_ROUTE "--metrics-http-route=/metrics"
  C07: &COLLECTOR_GRPC_PORT "--collector.grpc-port=14250"
  C08: &COLLECTOR_HTTP_PORT "--collector.http-port=14268"
  C09: &AGENT_BINARY_PORT "--processor.jaeger-binary.server-host-port=0.0.0.0:6832"
  C10: &AGENT_COMPACT_PORT "--processor.jaeger-compact.server-host-port=0.0.0.0:6831"
  C11: &AGENT_HTTP_PORT "--http-server.host-port=0.0.0.0:5778"
  C12: &AGENT_REPORTER_TYPE "--reporter.type=grpc"
  C13: &AGENT_REPORTER_ADDS "--reporter.grpc.host-port=jcollector_1:14250,jcollector_2:14250"
  C14: &CASSANDRA_SERVERS "--cassandra.servers=cas_1"
  C15: &CASSANDRA_KEYSPACE "--cassandra.keyspace=jaeger_keyspace"

networks:
  net:
    driver: "bridge"

x-jaeger-logging-defaults: &JAEGER_LOGGING_DEFAULTS
  driver: "json-file"
  options:
    max-size: "512m"

services:
  jaeger-query:
    image: "jaegertracing/jaeger-query:1.11.0"
    container_name: "jquery"
    hostname: "jquery"
    depends_on:
      - "jaeger-collector-1"
      - "jaeger-collector-2"
    networks:
      - "net"
    ports:
      - "16686:16686"
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      "--query.port=16686",
      *CASSANDRA_SERVERS,
      *CASSANDRA_KEYSPACE,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
    environment:
      - SPAN_STORAGE_TYPE=cassandra
  jaeger-agent-web:
    image: "jaegertracing/jaeger-agent:1.11.0"
    container_name: "jagent_web"
    hostname: "jagent_web"
    depends_on:
      - "jaeger-collector-1"
      - "jaeger-collector-2"
    networks:
      - "net"
    ports:
      - "6832:6832/udp"
      - "6831:6831/udp"
      - "5778:5778"
    expose:
      - "6832"
      - "6831"
      - "5778"
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      *AGENT_REPORTER_ADDS,
      *AGENT_REPORTER_TYPE,
      *AGENT_BINARY_PORT,
      *AGENT_COMPACT_PORT,
      *AGENT_HTTP_PORT,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
  jaeger-agent-service:
    image: "jaegertracing/jaeger-agent:1.11.0"
    container_name: "jagent_service"
    hostname: "jagent_service"
    depends_on:
      - "jaeger-collector-1"
      - "jaeger-collector-2"
    networks:
      - "net"
    ports:
      - "6842:6832/udp"
      - "6841:6831/udp"
      - "5788:5778"
    expose:
      - "6832"
      - "6831"
      - "5778"
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      *AGENT_REPORTER_ADDS,
      *AGENT_REPORTER_TYPE,
      *AGENT_BINARY_PORT,
      *AGENT_COMPACT_PORT,
      *AGENT_HTTP_PORT,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
  jaeger-agent-consumer:
    image: "jaegertracing/jaeger-agent:1.11.0"
    container_name: "jagent_consumer"
    hostname: "jagent_consumer"
    depends_on:
      - "jaeger-collector-1"
      - "jaeger-collector-2"
    networks:
      - "net"
    ports:
      - "6852:6832/udp"
      - "6851:6831/udp"
      - "5798:5778"
    expose:
      - "6832"
      - "6831"
      - "5778"
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      *AGENT_REPORTER_ADDS,
      *AGENT_REPORTER_TYPE,
      *AGENT_BINARY_PORT,
      *AGENT_COMPACT_PORT,
      *AGENT_HTTP_PORT,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
  jaeger-collector-1:
    image: "jaegertracing/jaeger-collector:1.11.0"
    container_name: "jcollector_1"
    hostname: "jcollector_1"
    networks:
      - "net"
    expose:
      - "14250" # grpc
      - "14268" # http (prometheus)
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      *COLLECTOR_GRPC_PORT,
      *COLLECTOR_HTTP_PORT,
      *CASSANDRA_SERVERS,
      *CASSANDRA_KEYSPACE,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
    environment:
      - SPAN_STORAGE_TYPE=cassandra
  jaeger-collector-2:
    image: "jaegertracing/jaeger-collector:1.11.0"
    container_name: "jcollector_2"
    hostname: "jcollector_2"
    networks:
      - "net"
    expose:
      - "14250" # grpc
      - "14268" # http (prometheus)
    restart: "always"
    logging:
      <<: *JAEGER_LOGGING_DEFAULTS
    command: [
      *COLLECTOR_GRPC_PORT,
      *COLLECTOR_HTTP_PORT,
      *CASSANDRA_SERVERS,
      *CASSANDRA_KEYSPACE,
      *METRICS_BACKEND,
      *METRICS_HTTP_ROUTE,
      *LOG_LEVEL_DEBUG
    ]
    environment:
      - SPAN_STORAGE_TYPE=cassandra