version: '2'
x-prom-environment-defaults:
  C1: &CONFIG_FILE "--config.file=/etc/prometheus/prometheus.yml"
  C2: &LOG_LEVEL "--log.level=info"
  C3: &LOG_FORMAT "--log.format=json"

networks:
  net:
    driver: "bridge"

#volumes:
#  cas_vol_1:
#    driver: "local"

x-prom-logging-defaults: &PROM_LOGGING_DEFAULTS
  driver: "json-file"
  options:
    max-size: "512m"

services:
  grafana:
    image: "grafana/grafana:6.1.2"
    container_name: "grafana"
    hostname: "grafana"
    networks:
      - "net"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    image: "prom/prometheus:v2.8.1"
    container_name: "prometheus"
    hostname: "prometheus"
    volumes:
      - /private/tmp/prom-master.yaml:/etc/prometheus/prometheus.yml
    networks:
      - "net"
    ports:
      - "9090:9090"
    depends_on:
      - machine_xx1_node
      - machine_xx2_node
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]
  machine_xx1_node:
    image: "prom/prometheus:v2.8.1"
    container_name: "machine_xx1_node"
    hostname: "machine_xx1_node"
    volumes:
      - /private/tmp/machine_xx1_node.yaml:/etc/prometheus/prometheus.yml
    networks:
      - "net"
    expose:
      - "9090"
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]
  machine_xx2_node:
    image: "prom/prometheus:v2.8.1"
    container_name: "machine_xx2_node"
    hostname: "machine_xx2_node"
    volumes:
      - /private/tmp/machine_xx2_node.yaml:/etc/prometheus/prometheus.yml
    networks:
      - "net"
    expose:
      - "9090"
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]