version: '2'
x-prom-environment-defaults:
  C1: &CONFIG_FILE "--config.file=/etc/prometheus/prometheus.yml"
  C2: &LOG_LEVEL "--log.level=info"
  C3: &LOG_FORMAT "--log.format=json"

networks:
  net:
    driver: "bridge"

volumes:
  grafana_vol:
    driver: "local"
  prometheus_vol:
    driver: "local"
  machine_xx1_node_vol:
    driver: "local"
  machine_xx2_node_vol:
    driver: "local"

x-prom-logging-defaults: &PROM_LOGGING_DEFAULTS
  driver: "json-file"
  options:
    max-size: "512m"

services:
  grafana:
    image: "grafana/grafana:6.1.2"
    container_name: "grafana"
    hostname: "grafana"
    volumes:
      - /private/tmp/grafana.ini:/etc/grafana/grafana.ini
      - grafana_vol:/var/lib/grafana
    networks:
      - "net"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DEFAULT_APP_MODE=production
      - GF_LOGGING_MODE="console file"
      - GF_LOGGING_LEVEL=info
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
  prometheus:
    image: "prom/prometheus:v2.8.1"
    container_name: "prometheus"
    hostname: "prometheus"
    volumes:
      - /private/tmp/prom-master.yaml:/etc/prometheus/prometheus.yml
      - prometheus_vol:/prometheus
    networks:
      - "net"
    ports:
      - "9090:9090"
    depends_on:
      - machine_xx1_node
      - machine_xx2_node
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]
  machine_xx1_node:
    image: "prom/prometheus:v2.8.1"
    container_name: "machine_xx1_node"
    hostname: "machine_xx1_node"
    volumes:
      - /private/tmp/machine_xx1_node.yaml:/etc/prometheus/prometheus.yml
      - machine_xx1_node_vol:/prometheus
    networks:
      - "net"
    expose:
      - "9090"
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]
  machine_xx2_node:
    image: "prom/prometheus:v2.8.1"
    container_name: "machine_xx2_node"
    hostname: "machine_xx2_node"
    volumes:
      - /private/tmp/machine_xx2_node.yaml:/etc/prometheus/prometheus.yml
      - machine_xx2_node_vol:/prometheus
    networks:
      - "net"
    expose:
      - "9090"
    restart: "always"
    logging:
      <<: *PROM_LOGGING_DEFAULTS
    command: [
      "--web.listen-address=0.0.0.0:9090",
      *CONFIG_FILE,
      *LOG_LEVEL,
      *LOG_FORMAT,
    ]