version: '2'
x-es-environment-defaults:
  C1: &DISCOVERY_SEED_HOSTS "discovery.seed_hosts=es_1:9300,es_2:9300,es_3:9300"
  C2: &CLUSTER_INITIAL_MASTER_NODES "cluster.initial_master_nodes=es_1,es_2,es_3"
  C4: &ES_JAVA_OPTS "ES_JAVA_OPTS=\
      -Xms256m \
      -Xmx256m \
    "

x-es-ulimit-defaults: &ES_ULIMIT_DEFAULTS
  nproc: 65535
  nofile:
    soft: 65535
    hard: 65535
  memlock:
    soft: -1
    hard: -1

networks:
  net:
    driver: "bridge"

volumes:
  es_vol_1_logs:
    driver: "local"
  es_vol_1_data:
    driver: "local"
  es_vol_2_logs:
    driver: "local"
  es_vol_2_data:
    driver: "local"
  es_vol_3_logs:
    driver: "local"
  es_vol_3_data:
    driver: "local"

services:
  kibana:
    image: "kibana:7.0.0"
    container_name: "kibana"
    hostname: "kibana"
    depends_on:
      - "es_1"
      - "es_2"
      - "es_3"
    networks:
      - "net"
    ports:
      - "5601:5601"
    restart: "always"
    environment:
      - SERVER_PORT=5601
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=es_cluster
      - ELASTICSEARCH_HOSTS=es_1:9201,es_2:9202,es_3:9203
      - KIBANA_INDEX=.kibana
      - DIBANA_DEFAULTAPPID=home
      - ELASTICSEARCH_PINGTIMEOUT=1500
      - ELASTICSEARCH_REQUESTTIMEOUT=10000
      - ELASTICSEARCH_LOGQUERIES=false
  filebeat:
    image: "elastic/filebeat:7.0.0"
    container_name: "filebeat"
    hostname: "filebeat"
    depends_on:
      - "es_1"
      - "es_2"
      - "es_3"
    networks:
      - "net"
    volumes:
      - /private/tmp/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - /private/tmp/logs/app:/tmp/app/logs
    restart: "always"
    environment:
      - ES_HOSTS=es_1:9201,es_2:9202,es_3:9203
      - LOGGING_LEVEL=debug
  es_1:
    image: "elasticsearch:7.0.0"
    container_name: "es_1"
    hostname: "es_1"
    volumes:
      - es_vol_1_data:/usr/share/elasticsearch/data
      - es_vol_1_logs:/usr/share/elasticsearch/logs
      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - "net"
    ports:
      - "9201:9201"
    expose:
      - "9300"
    restart: "always"
    environment:
      - node.name=es_1
      - http.port=9201
      - node.master=true
      - node.data=true
      - *DISCOVERY_SEED_HOSTS
      - *CLUSTER_INITIAL_MASTER_NODES
      - *ES_JAVA_OPTS
    ulimits:
      <<: *ES_ULIMIT_DEFAULTS
  es_2:
    image: "elasticsearch:7.0.0"
    container_name: "es_2"
    hostname: "es_2"
    volumes:
      - es_vol_2_data:/usr/share/elasticsearch/data
      - es_vol_2_logs:/usr/share/elasticsearch/logs
      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - "net"
    ports:
      - "9202:9202"
    expose:
      - "9300"
    restart: "always"
    environment:
      - node.name=es_2
      - http.port=9202
      - node.master=true
      - node.data=true
      - *DISCOVERY_SEED_HOSTS
      - *CLUSTER_INITIAL_MASTER_NODES
      - *ES_JAVA_OPTS
    ulimits:
      <<: *ES_ULIMIT_DEFAULTS
  es_3:
    image: "elasticsearch:7.0.0"
    container_name: "es_3"
    hostname: "es_3"
    volumes:
      - es_vol_3_data:/usr/share/elasticsearch/data
      - es_vol_3_logs:/usr/share/elasticsearch/logs
      - /private/tmp/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - "net"
    ports:
      - "9203:9203"
    expose:
      - "9300"
    restart: "always"
    environment:
      - node.name=es_3
      - http.port=9203
      - node.master=true
      - node.data=true
      - *DISCOVERY_SEED_HOSTS
      - *CLUSTER_INITIAL_MASTER_NODES
      - *ES_JAVA_OPTS
    ulimits:
      <<: *ES_ULIMIT_DEFAULTS