version: '2'
x-kafka-environment-defaults: &KAFKA_ENV_DEFAULTS
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
  KAFKA_NUM_NETWORK_THREADS: 3
  KAFKA_NUM_IO_THREADS: 8
  KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
  KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
  KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
  KAFKA_LOG_DIRS: "/tmp/kafka-logs"
  KAFKA_NUM_PARTITIONS: 3
  KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
  #KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
  KAFKA_LOG_RETENTION_HOURS: 168
  KAFKA_LOG_RETENTION_BYTES: 1073741824
  KAFKA_LOG_SEGMENT_BYTES: 1073741824
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

x-kafka-logging-defaults: &KAFKA_LOGGING_DEFAULTS
  driver: "json-file"
  options:
    max-size: "512m"

networks:
  kafka-net:
    driver: "bridge"

services:
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    hostname: "zookeeper"
    container_name: "zookeeper"
    networks:
      - "kafka-net"
    ports:
      - "2181:2181"
    restart: "always"
    logging:
      <<: *KAFKA_LOGGING_DEFAULTS
  # the working directory in container is "/opt/kafka", if volumes related is necessary
  kafka_1:
    image: "wurstmeister/kafka:2.12-2.2.0"
    hostname: "kafka_1"
    container_name: "kafka_1"
    depends_on:
      - "zookeeper"
    networks:
      - "kafka-net"
    ports:
      - "19092:19092"
    expose:
      - "19093"
    restart: "always"
    logging:
      <<: *KAFKA_LOGGING_DEFAULTS
    environment:
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:19093,OUTSIDE://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka_1:19093,OUTSIDE://127.0.0.1:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 0
      <<: *KAFKA_ENV_DEFAULTS
  kafka_2:
    image: "wurstmeister/kafka:2.12-2.2.0"
    hostname: "kafka_2"
    container_name: "kafka_2"
    depends_on:
      - "zookeeper"
    networks:
      - "kafka-net"
    ports:
      - "29092:29092"
    expose:
      - "29093"
    restart: "always"
    logging:
      <<: *KAFKA_LOGGING_DEFAULTS
    environment:
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka_2:29093,OUTSIDE://127.0.0.1:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      <<: *KAFKA_ENV_DEFAULTS
  kafka_3:
    image: "wurstmeister/kafka:2.12-2.2.0"
    hostname: "kafka_3"
    container_name: "kafka_3"
    depends_on:
      - "zookeeper"
    networks:
      - "kafka-net"
    ports:
      - "39092:39092"
    expose:
      - "39093"
    restart: "always"
    logging:
      <<: *KAFKA_LOGGING_DEFAULTS
    environment:
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:39093,OUTSIDE://0.0.0.0:39092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka_3:39093,OUTSIDE://127.0.0.1:39092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 2
      <<: *KAFKA_ENV_DEFAULTS