{
 "title": "Filebeat",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(filebeat_uptime_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Harvester",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_filebeat_harvester{instance=~\"$node\"}",
     "legendFormat": "{{instance}}-{{harvester}}"
    }
   ]
  },
  {
   "title": "IO errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(filebeat_libbeat_output_read_errors{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-read-errors"
    },
    {
     "expr": "increase(filebeat_libbeat_output_write_errors{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-write-errors"
    }
   ]
  },
  {
   "title": "Filebeat events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(filebeat_filebeat_events{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{event}}"
    }
   ]
  },
  {
   "title": "Output events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(filebeat_libbeat_output_events{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Pipeline events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(filebeat_libbeat_pipeline_events{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Pipeline queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(filebeat_libbeat_pipeline_queue{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  }
 ]
}