{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "query": "go-apps" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "node",
    "query": "label_values(go_memstats_alloc_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "{{instance}}-inuse" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "{{instance}}-idle" }
   ]
  },
  {
   "title": "Heap memory trends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$interval])",
     "legendFormat": "{{instance}}-alloc"
    },
    {
     "expr": "rate(go_memstats_frees_total[$interval])",
     "legendFormat": "{{instance}}-frees"
    }
   ]
  },
  {
   "title": "Heap objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap system alloc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "{{instance}}-released"
    },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "{{instance}}-alloc" }
   ]
  },
  {
   "title": "GC rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Next gc target",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.25, go_gc_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}-0.25"
    },
    {
     "expr": "quantile(0.5, go_gc_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}-0.5"
    },
    {
     "expr": "quantile(0.9, go_gc_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}-0.9"
    }
   ]
  },
  {
   "title": "Goroutines count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Threads count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}