{
 "title": "Jaeger Collector",
 "description": "Jaeger Collector dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(jaeger_collector_queue_length, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jaeger_collector_traces_received_total{debug=\"false\",format=\"jaeger\",svc=~\"app.*\",instance=~\"$node\"}[1m]) ",
     "legendFormat": "{{instance}}-{{svc}}"
    }
   ]
  },
  {
   "title": "Traces rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jaeger_collector_traces_rejected_total{debug=\"false\",format=\"jaeger\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{svc}}"
    }
   ]
  },
  {
   "title": "Spans received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jaeger_collector_spans_received_total{debug=\"false\",format=\"jaeger\",svc=~\"app.*\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{svc}}"
    }
   ]
  },
  {
   "title": "Spans dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jaeger_collector_spans_dropped_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{svc}}"
    }
   ]
  },
  {
   "title": "Spans rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jaeger_collector_spans_rejected_total{debug=\"false\",format=\"jaeger\",svc=~\"app.*\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}-{{svc}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_collector_queue_length{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Span queue latency - 95 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_collector_in_queue_latency_bucket{instance=~\"$node\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Save latency - 95 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_collector_save_latency_bucket{instance=~\"$node\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Cassandra attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_cassandra_attempts_total{table=\"traces\",instance=~\"$node\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_cassandra_errors_total{table=\"traces\",instance=~\"$node\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}