scrape_configs:
  - job_name: 'node'
    scrape_interval: 15s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_CLIENT:9100"
          - "HOST_IP_STORAGE:9100"
          - "HOST_IP_KAFKA_1:9100"
          - "HOST_IP_KAFKA_2:9100"
          - "HOST_IP_ES_1:9100"
          - "HOST_IP_ES_2:9100"
          - "HOST_IP_MONITOR:9100"
          - "HOST_IP_WEB:9100"
          - "HOST_IP_SERVICE:9100"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'cadvisor'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_CLIENT:8080"
          - "HOST_IP_STORAGE:8080"
          - "HOST_IP_KAFKA_1:8080"
          - "HOST_IP_KAFKA_2:8080"
          - "HOST_IP_ES_1:8080"
          - "HOST_IP_ES_2:8080"
          - "HOST_IP_MONITOR:8080"
          - "HOST_IP_WEB:8080"
          - "HOST_IP_SERVICE:8080"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_MONITOR:9090"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'mysqld'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_STORAGE:9104"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'memcached'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_STORAGE:9150"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'jaeger-agent'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_WEB:5778"
          - "HOST_IP_SERVICE:5778"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'jaeger-collector'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_MONITOR:14268"
          - "HOST_IP_MONITOR:14269"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'kafka'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_KAFKA_1:7071"
          - "HOST_IP_KAFKA_1:7171"
          - "HOST_IP_KAFKA_2:7271"
          - "HOST_IP_KAFKA_2:7371"

  - job_name: 'kafka-exporter'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_KAFKA_2:9308"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'filebeat-exporter'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_WEB:9479"
          - "HOST_IP_SERVICE:9479"

  - job_name: 'elasticsearch-exporter'
    scrape_interval: 60s
    scrape_timeout: 30s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_ES_2:9114"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(\
          go_gc_duration_seconds|\
          go_gc_duration_seconds_sum|\
          go_gc_duration_seconds_count|\
          go_goroutines|\
          go_info|\
          go_memstats_alloc_bytes|\
          go_memstats_alloc_bytes_total|\
          go_memstats_buck_hash_sys_bytes|\
          go_memstats_frees_total|\
          go_memstats_gc_cpu_fraction|\
          go_memstats_gc_sys_bytes|\
          go_memstats_heap_alloc_bytes|\
          go_memstats_heap_idle_bytes|\
          go_memstats_heap_inuse_bytes|\
          go_memstats_heap_objects|\
          go_memstats_heap_released_bytes|\
          go_memstats_heap_sys_bytes|\
          go_memstats_last_gc_time_seconds|\
          go_memstats_lookups_total|\
          go_memstats_mallocs_total|\
          go_memstats_mcache_inuse_bytes|\
          go_memstats_mcache_sys_bytes|\
          go_memstats_mspan_inuse_bytes|\
          go_memstats_mspan_sys_bytes|\
          go_memstats_next_gc_bytes|\
          go_memstats_other_sys_bytes|\
          go_memstats_stack_inuse_bytes|\
          go_memstats_stack_sys_bytes|\
          go_memstats_sys_bytes|\
          go_threads|\
        )"
        action: drop

  - job_name: 'go-apps'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - "HOST_IP_WEB:8000" # web
          - "HOST_IP_SERVICE:8001" # service
          - "HOST_IP_SERVICE:8002" # consumer